name: CI
on: [push]
jobs:
  install:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: NPM prepare
        uses: karpov-kir/github-actions/npm-prepare@main

  build:
    runs-on: ubuntu-22.04
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: NPM prepare
        uses: karpov-kir/github-actions/npm-prepare@main

      - name: Build
        run: npm run build

  lint:
    runs-on: ubuntu-22.04
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: NPM prepare
        uses: karpov-kir/github-actions/npm-prepare@main

      - name: Lint
        run: npm run lint

  test:
    runs-on: ubuntu-22.04
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: NPM prepare
        uses: karpov-kir/github-actions/npm-prepare@main

      - name: Initialize coverage cache
        uses: actions/cache@v3
        with:
          path: ./coverage
          key: ${{ runner.os }}-coverage-${{ github.sha }}

      - name: Test
        run: npm run test

  analyze:
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore coverage cache 
        uses: actions/cache@v3
        with:
          path: ./coverage
          key: ${{ runner.os }}-coverage-${{ github.sha }}

      - name: SonarQube scan
        uses: karpov-kir/github-actions/sonarqube-scan@main
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          sonar-host-url: ${{ secrets.SONAR_HOST_URL }}
